services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  flask:
    build: ./backend
    container_name: flask_container
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
